// Code generated by alicloud-aiops-cruise; DO NOT EDIT manually.
// Operation:    DescribeInstanceDasPro
// SDK Method:   client.DescribeInstanceDasPro (性能洞察)
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       RegionId 字段仍从 env 读取。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
//
// Usage:
//   cd alicloud-aiops-cruise/assets/code-snippets
//   INSTANCE_ID=rm-xxx go run das_performance_insight.go

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	instanceID := os.Getenv("INSTANCE_ID")
	if instanceID == "" {
		log.Fatal("INSTANCE_ID is required")
	}

	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	// 查询实例是否已开启 DAS 专业版
	getDasProReq := &das.DescribeInstanceDasProRequest{
		InstanceId: tea.String(instanceID),
	}

	dasProResp, err := c.DescribeInstanceDasPro(getDasProReq)
	if err != nil {
		log.Fatalf("DescribeInstanceDasPro failed: %v", err)
	}

	// 关键字段提示:
	// $.Data.DasProOn   -> true/false（是否已开启 DAS 专业版）
	// 未开启则跳过性能洞察

	result := map[string]interface{}{
		"das_pro_status": dasProResp.Body,
	}

	out, _ := json.MarshalIndent(result, "", "  ")
	fmt.Println(string(out))
}