// Code generated by alicloud-aiops-cruise; DO NOT EDIT manually.
// Reference: references/integration.md §Go Runtime Bootstrap
//
// Client 工厂 — 从环境变量读取 AK/SK，构造 DAS Client。
// 被 das_slow_query.go / das_performance_insight.go / das_cache_analysis.go 引用。
//
// 约束：
// - 绝不打印或回显 ALIBABA_CLOUD_ACCESS_KEY_SECRET
// - Endpoint 由调用者传入（DAS 固定使用 das.cn-shanghai.aliyuncs.com）
package main

import (
	"fmt"
	"os"

	openapi "github.com/alibabacloud-go/darabonba-openapi/v2/client"
	das "github.com/alibabacloud-go/das-20200116/v5/client"
)

// NewClient constructs a DAS client using env credentials.
// MUST be the only place credentials are referenced.
func NewClient(endpoint string) (*das.Client, error) {
	ak := os.Getenv("ALIBABA_CLOUD_ACCESS_KEY_ID")
	sk := os.Getenv("ALIBABA_CLOUD_ACCESS_KEY_SECRET")
	if ak == "" || sk == "" {
		return nil, fmt.Errorf("missing ALIBABA_CLOUD_ACCESS_KEY_ID or ALIBABA_CLOUD_ACCESS_KEY_SECRET")
	}

	config := &openapi.Config{
		AccessKeyId:     &ak,
		AccessKeySecret: &sk,
		Endpoint:        &endpoint,
	}
	return das.NewClient(config)
}