// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    CreateKillInstanceSessionTask
// SDK Method:   client.CreateKillInstanceSessionTask
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-createkillinstancesessiontask
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx SESSION_IDS=12345,67890 go run create_kill_session_task.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求
	// Destructive action: always present session list from GetSessionList
	// to the user and require explicit confirmation before executing.
	req := &das.CreateKillInstanceSessionTaskRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		// Optional filter parameters per OpenAPI spec:
		//   SessionIds (comma-separated), User, Host, Db, Command, Time (seconds)
		SessionIds: tea.String(os.Getenv("SESSION_IDS")),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.CreateKillInstanceSessionTask(req)
	if err != nil {
		log.Fatalf("CreateKillInstanceSessionTask failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> true 表示杀会话任务已提交
	// $.RequestId   -> 用于工单/日志关联
	// 验证：随后调用 GetSessionList 确认目标 session 已消失
}
