// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    CreateSqlLimitTask
// SDK Method:   client.CreateSqlLimitTask
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-createsqllimittask
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx SQL_TYPE=UPDATE SQL_KEYWORDS="order~status" \
//     MAX_CONCURRENCY=3 DURATION=600 \
//     go run create_sql_limit_task.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	maxConcurrency, _ := strconv.ParseInt(os.Getenv("MAX_CONCURRENCY"), 10, 64)
	duration, _ := strconv.ParseInt(os.Getenv("DURATION"), 10, 64)

	// 1. 构造请求
	req := &das.CreateSqlLimitTaskRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId:     tea.String(os.Getenv("INSTANCE_ID")),
		SqlType:        tea.String(os.Getenv("SQL_TYPE")),        // SELECT / UPDATE / DELETE
		MaxConcurrency: tea.Int64(maxConcurrency),                // >= 1
		Duration:       tea.Int64(duration),                      // seconds
		SqlKeywords:    tea.String(os.Getenv("SQL_KEYWORDS")),    // separated by ~
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.CreateSqlLimitTask(req)
	if err != nil {
		log.Fatalf("CreateSqlLimitTask failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> true 表示限流任务创建成功
	// $.RequestId   -> 用于工单/日志关联
	// 验证：调用 DescribeSqlLimitTasks 确认 taskId 状态为 ACTIVE
}
