// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    CreateLatestDeadLockAnalysis
// SDK Method:   client.CreateLatestDeadLockAnalysis
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-createlatestdeadlockanalysis
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx NODE_ID=pi-xxx go run create_deadlock_analysis.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求 (MySQL / PolarDB / PolarDB-X only)
	req := &das.CreateLatestDeadLockAnalysisRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		NodeId:     tea.String(os.Getenv("NODE_ID")), // optional for non-cluster
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.CreateLatestDeadLockAnalysis(req)
	if err != nil {
		log.Fatalf("CreateLatestDeadLockAnalysis failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> true 表示分析任务创建成功
	// $.RequestId   -> 用于工单/日志关联
}
