// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    AddHDMInstance
// SDK Method:   client.AddHDMInstance
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-addhdminstance
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx ENGINE=MySQL go run create_hdm_instance.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求 (字段名与 OpenAPI Request Schema 1:1 对齐)
	req := &das.AddHDMInstanceRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		Engine:     tea.String(os.Getenv("ENGINE")),
		// Optional: VpcId, Ip, Port for non-RDS instances
	}

	// 2. 调用 Client (DAS is single-region; endpoint is fixed to cn-shanghai)
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.AddHDMInstance(req)
	if err != nil {
		// 错误信息必须包含 RequestId, 便于回溯
		log.Fatalf("AddHDMInstance failed: %v", err)
	}

	// 3. 序列化输出 (便于 Agent 解析)
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示 (供 Agent 提取)
	// $.Data        -> true 表示注册成功
	// $.Code        -> "200" 表示请求成功 (仍需校验 $.Success)
	// $.RequestId   -> 用于工单/日志关联
}
