// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetAutoScalingConfig
// SDK Method:   client.GetAutoScalingConfig
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getautoscalingconfig
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx go run describe_auto_scaling_config.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求
	req := &das.GetAutoScalingConfigRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetAutoScalingConfig(req)
	if err != nil {
		log.Fatalf("GetAutoScalingConfig failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data.enableAutoScaling  -> boolean
	// $.Data.maxStorage         -> GB
	// $.Data.maxSpecification   -> e.g. "8C32G"
	// $.Data.scalingPolicies    -> "STORAGE,SPEC"
	// $.RequestId               -> 用于工单/日志关联
}
