// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetRunningSqlConcurrencyControlRules
// SDK Method:   client.GetRunningSqlConcurrencyControlRules
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getrunningsqlconcurrencycontrolrules
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx PAGE_NO=1 PAGE_SIZE=10 \
//     go run describe_running_sql_concurrency_rules.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	pageNo, _ := strconv.ParseInt(os.Getenv("PAGE_NO"), 10, 32)
	if pageNo == 0 {
		pageNo = 1
	}
	pageSize, _ := strconv.ParseInt(os.Getenv("PAGE_SIZE"), 10, 32)
	if pageSize == 0 {
		pageSize = 10
	}

	// 1. 构造请求
	req := &das.GetRunningSqlConcurrencyControlRulesRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		PageNo:     tea.Int32(int32(pageNo)),
		PageSize:   tea.Int32(int32(pageSize)),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetRunningSqlConcurrencyControlRules(req)
	if err != nil {
		log.Fatalf("GetRunningSqlConcurrencyControlRules failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data.Total                       -> 正在运行的规则总数
	// $.Data.List.runningRules[]         -> 规则列表
	//   [].ItemId                        -> 用于 DisableSqlConcurrencyControl
	//   [].SqlType, SqlKeywords, MaxConcurrency
	//   [].ConcurrencyControlTime, StartTime
	//   [].Status                        -> 始终为 "Open"
	// $.RequestId                        -> 用于工单/日志关联
}
