// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    DescribeSqlLimitTasks
// SDK Method:   client.DescribeSqlLimitTasks
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-describesqllimittasks
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx SQL_TYPE=UPDATE STATUS=ACTIVE \
//     go run describe_sql_limit_tasks.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求
	req := &das.DescribeSqlLimitTasksRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		// Optional filters per OpenAPI spec:
		//   SqlType (SELECT / UPDATE / DELETE), Status (ACTIVE / EXPIRED)
		SqlType: tea.String(os.Getenv("SQL_TYPE")),
		Status:  tea.String(os.Getenv("STATUS")),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.DescribeSqlLimitTasks(req)
	if err != nil {
		log.Fatalf("DescribeSqlLimitTasks failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data[]           -> 限流任务列表
	//   [].taskId        -> 限流任务 ID
	//   [].sqlKeywords, maxConcurrency, status, createTime
	// $.RequestId        -> 用于工单/日志关联
	// 验证：CreateSqlLimitTask 后确认 taskId 状态 == "ACTIVE"
}
