// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetSpaceSummary
// SDK Method:   client.GetSpaceSummary
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getspacesummary
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx go run describe_space_summary.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求
	req := &das.GetSpaceSummaryRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		// Optional: DbName for narrowing scope
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetSpaceSummary(req)
	if err != nil {
		log.Fatalf("GetSpaceSummary failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data.totalSize   -> 总空间 (bytes)
	// $.Data.dataSize    -> 数据占用
	// $.Data.indexSize   -> 索引占用
	// $.Data.freeSize    -> 空闲空间; 使用率 > 85% 触发告警
	// $.RequestId        -> 用于工单/日志关联
}
