// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetPfsSqlSamples
// SDK Method:   client.GetPfsSqlSamples
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getpfssqlsamples
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx \
//   START_TIME=1747198800000 END_TIME=1747202400000 \
//     go run describe_pfs_sql_samples.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	startTime, _ := strconv.ParseInt(os.Getenv("START_TIME"), 10, 64)
	endTime, _ := strconv.ParseInt(os.Getenv("END_TIME"), 10, 64)

	// 1. 构造请求 (requires DAS Pro)
	req := &das.GetPfsSqlSamplesRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		StartTime:  tea.Int64(startTime), // Unix ms
		EndTime:    tea.Int64(endTime),
		// Optional: SqlId, DbName, UserName, MinExecTime
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetPfsSqlSamples(req)
	if err != nil {
		log.Fatalf("GetPfsSqlSamples failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> Performance Insight SQL 样本 (等待事件、执行时间轴、SQL 文本)
	// $.RequestId   -> 用于工单/日志关联
	// 配合：与 GetQueryOptimizeData 的 sqlList 交叉比对
}
