// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetAutonomousNotifyEventsInRange
// SDK Method:   client.GetAutonomousNotifyEventsInRange
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getautonomousnotifyeventsinrange
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx \
//   START_TIME="2026-05-01T00:00:00Z" END_TIME="2026-05-14T23:59:59Z" \
//     go run describe_autonomous_events.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求
	req := &das.GetAutonomousNotifyEventsInRangeRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		StartTime:  tea.String(os.Getenv("START_TIME")), // ISO 8601
		EndTime:    tea.String(os.Getenv("END_TIME")),
		// Optional: EventTypes (e.g. "AUTO_SCALING,SQL_THROTTLING,SPACE_OPTIMIZATION")
		EventTypes: tea.String(os.Getenv("EVENT_TYPES")),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetAutonomousNotifyEventsInRange(req)
	if err != nil {
		log.Fatalf("GetAutonomousNotifyEventsInRange failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data[]        -> 自治事件列表
	//   [].eventId    -> 用于 GetAutonomousNotifyEventContent
	//   [].eventType, eventStatus, startTime
	// $.RequestId     -> 用于工单/日志关联
}
