// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetDBInstanceConnectivityDiagnosis
// SDK Method:   client.GetDBInstanceConnectivityDiagnosis
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getdbinstanceconnectivitydiagnosis
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx SRC_IP=10.0.0.5 \
//     go run diagnose_db_instance_connectivity.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	srcPort, _ := strconv.ParseInt(os.Getenv("SRC_PORT"), 10, 64)

	// 1. 构造请求
	// Security: if DbPassword is required, use a temporary test account.
	// NEVER pass production admin credentials in diagnostic calls.
	req := &das.GetDBInstanceConnectivityDiagnosisRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		SrcIp:      tea.String(os.Getenv("SRC_IP")), // source IPv4/IPv6
		// Optional: SrcPort, DbUser, DbPassword (use with caution)
		SrcPort: tea.Int64(srcPort),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetDBInstanceConnectivityDiagnosis(req)
	if err != nil {
		log.Fatalf("GetDBInstanceConnectivityDiagnosis failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data.connectivityResult   -> "REACHABLE" / "UNREACHABLE"
	// $.Data.failureReason        -> UNREACHABLE 时的具体原因
	// $.Data.suggestedActions     -> 建议的修复动作
	// $.RequestId                 -> 用于工单/日志关联
}
