// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    DisableSqlConcurrencyControl
// SDK Method:   client.DisableSqlConcurrencyControl
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-disablesqlconcurrencycontrol
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx ITEM_ID=12345 go run disable_sql_concurrency_control.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	itemId, _ := strconv.ParseInt(os.Getenv("ITEM_ID"), 10, 64)

	// 1. 构造请求
	req := &das.DisableSqlConcurrencyControlRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		ItemId:     tea.Int64(itemId), // from GetRunningSqlConcurrencyControlRules
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.DisableSqlConcurrencyControl(req)
	if err != nil {
		log.Fatalf("DisableSqlConcurrencyControl failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> "Null" 字符串表示成功
	// $.Code        -> "200"
	// $.Success     -> "true"
	// $.RequestId   -> 用于工单/日志关联
	// 验证：调用 GetRunningSqlConcurrencyControlRules 确认该 ItemId 已消失
}
