// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    GetSqlConcurrencyControlKeywordsFromSqlText
// SDK Method:   client.GetSqlConcurrencyControlKeywordsFromSqlText
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-getsqlconcurrencycontrolkeywordsfromsqltext
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx \
//   SQL_TEXT="SELECT * FROM orders WHERE status = 'pending'" \
//     go run extract_sql_concurrency_keywords.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求
	// Returns templated keywords (e.g. "SELECT~FROM~orders~WHERE~status").
	// To throttle a specific parameter value, append it with "~" before
	// passing the result to EnableSqlConcurrencyControl.
	req := &das.GetSqlConcurrencyControlKeywordsFromSqlTextRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
		SqlText:    tea.String(os.Getenv("SQL_TEXT")),
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.GetSqlConcurrencyControlKeywordsFromSqlText(req)
	if err != nil {
		log.Fatalf("GetSqlConcurrencyControlKeywordsFromSqlText failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> 模板化后的 SQL 关键词 (用 ~ 分隔)
	// $.RequestId   -> 用于工单/日志关联
	// 工作流：先调用本接口获得 keywords → 人工确认/调整 → 传给 EnableSqlConcurrencyControl
}
