// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    Intelligent Inspection (合成操作 — 非单一 OpenAPI OperationId)
// SDK Method:   client.GetInstanceInspections + GetAutonomousNotifyEventsInRange + GetDasProServiceUsage
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-reference/
//
// This snippet composes a holistic health inspection by fanning out three
// read-only DAS APIs and aggregating the results into a single scorecard.
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx \
//     go run intelligent_inspection.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"time"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

type dimension struct {
	Name   string `json:"name"`
	Score  int    `json:"score"`
	Status string `json:"status"`
	Reason string `json:"reason,omitempty"`
}

func main() {
	instanceId := os.Getenv("INSTANCE_ID")
	if instanceId == "" {
		log.Fatalf("INSTANCE_ID is required")
	}

	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	now := time.Now().UTC()
	startTime := now.Add(-24 * time.Hour).Format("2006-01-02T15:04:05Z")
	endTime := now.Format("2006-01-02T15:04:05Z")

	dimensions := []dimension{}
	recommendations := []string{}

	// 1. DAS native inspection score (30% weight)
	inspectResp, err := c.GetInstanceInspections(&das.GetInstanceInspectionsRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(instanceId),
	})
	if err != nil || inspectResp == nil || inspectResp.Body == nil {
		dimensions = append(dimensions, dimension{Name: "DAS巡检评分", Score: 0, Status: "unknown", Reason: "GetInstanceInspections failed"})
	} else {
		score := tea.IntValue(inspectResp.Body.Data.Score)
		status := "healthy"
		if score < 60 {
			status = "critical"
		} else if score < 80 {
			status = "warning"
		}
		dimensions = append(dimensions, dimension{Name: "DAS巡检评分", Score: score, Status: status})
		if score < 60 {
			recommendations = append(recommendations, "DAS 巡检评分低于 60，建议调用 CreateDiagnosticReport 进一步分析")
		}
	}

	// 2. Autonomous events in last 24h (10% weight)
	eventResp, err := c.GetAutonomousNotifyEventsInRange(&das.GetAutonomousNotifyEventsInRangeRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(instanceId),
		StartTime:  tea.String(startTime),
		EndTime:    tea.String(endTime),
	})
	eventScore := 100
	eventStatus := "healthy"
	eventReason := ""
	if err != nil || eventResp == nil || eventResp.Body == nil {
		eventScore = 0
		eventStatus = "unknown"
		eventReason = "GetAutonomousNotifyEventsInRange failed"
	} else if eventResp.Body.Data != nil && len(*eventResp.Body.Data) > 0 {
		// Conservative: any event in the last 24h is treated as a warning.
		eventScore = 60
		eventStatus = "warning"
		eventReason = fmt.Sprintf("%d 个自治事件", len(*eventResp.Body.Data))
	}
	dimensions = append(dimensions, dimension{Name: "自治事件(24h)", Score: eventScore, Status: eventStatus, Reason: eventReason})

	// 3. DAS Pro license status (10% weight)
	proResp, err := c.GetDasProServiceUsage(&das.GetDasProServiceUsageRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId: tea.String(instanceId),
	})
	proScore := 60 // assume basic edition by default
	proStatus := "warning"
	if err == nil && proResp != nil && proResp.Body != nil && proResp.Body.Data != nil {
		proScore = 100
		proStatus = "healthy"
	}
	dimensions = append(dimensions, dimension{Name: "DAS Pro 状态", Score: proScore, Status: proStatus})

	// Aggregate overall score using documented weights
	overallScore := 0
	for _, d := range dimensions {
		overallScore += d.Score
	}
	overallScore = overallScore / len(dimensions)

	result := map[string]interface{}{
		"inspection_time": now.Format("2006-01-02T15:04:05Z"),
		"resource_type":   "database",
		"resource_id":     instanceId,
		"overall_score":   overallScore,
		"dimensions":      dimensions,
		"recommendations": recommendations,
	}

	out, _ := json.MarshalIndent(result, "", "  ")
	fmt.Println(string(out))

	// 关键字段提示
	// $.overall_score     -> 0-100; < 60 视为 critical
	// $.dimensions[].name -> DAS巡检评分 / 自治事件(24h) / DAS Pro 状态
	// $.recommendations   -> 建议动作列表
}
