// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    SetAutoScalingConfig
// SDK Method:   client.SetAutoScalingConfig
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       但 RegionId 字段仍从 env 读取，用户应设 ALIBABA_CLOUD_REGION_ID=cn-shanghai。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/das/developer-reference/api-das-2020-01-16-setautoscalingconfig
//
// Usage:
//   cd alicloud-das-ops/assets/code-snippets
//   INSTANCE_ID=rm-xxx ENABLE_AUTO_SCALING=true \
//   MAX_STORAGE=1000 MAX_SPEC="8C32G" \
//     go run set_auto_scaling_config.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	enable := os.Getenv("ENABLE_AUTO_SCALING") == "true"
	maxStorage, _ := strconv.ParseInt(os.Getenv("MAX_STORAGE"), 10, 64)

	// 1. 构造请求
	// Safety gate: auto-scaling may trigger instance restart or connection
	// flash. Confirm with user before enabling on production instances.
	req := &das.SetAutoScalingConfigRequest{
		RegionId: tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceId:       tea.String(os.Getenv("INSTANCE_ID")),
		EnableAutoScaling: tea.Bool(enable),
		MaxStorage:       tea.Int64(maxStorage),               // GB
		MaxSpecification: tea.String(os.Getenv("MAX_SPEC")),   // e.g. "8C32G"
		ScalingPolicies:  tea.String(os.Getenv("SCALING_POLICIES")), // "STORAGE,SPEC"
	}

	// 2. 调用 Client
	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.SetAutoScalingConfig(req)
	if err != nil {
		log.Fatalf("SetAutoScalingConfig failed: %v", err)
	}

	// 3. 序列化输出
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示
	// $.Data        -> true 表示配置已保存
	// $.RequestId   -> 用于工单/日志关联
	// 验证：调用 GetAutoScalingConfig 确认 enableAutoScaling == true
}
