#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    ActivateTemplateMCP
# HTTP Method:  PATCH
# Endpoint:     https://agentrun.${REGION}.aliyuncs.com/2025-09-10/templates/${TEMPLATE_NAME}/mcp/activate
# Plane:        control
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Activate Template MCP

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${TEMPLATE_NAME:?missing TEMPLATE_NAME}"
# Comma-separated list of MCP tool names. Available tools:
#   health, run_code, read_file, write_file, file_system_list,
#   file_system_stat, file_system_download, file_system_mkdir,
#   file_system_move, file_system_remove, file_system_upload,
#   process_exec_cmd, process_tty, process_list, process_stat,
#   process_kill, list_contexts, create_context, get_context, delete_context
ENABLED_TOOLS_CSV="${ENABLED_TOOLS_CSV:-health,run_code,read_file,write_file,file_system_list,process_exec_cmd}"
TRANSPORT="${TRANSPORT:-streamable-http}"

# Convert CSV to JSON array via jq.
ENABLED_TOOLS_JSON=$(jq -nR --arg csv "$ENABLED_TOOLS_CSV" '($csv | split(","))')

# ---- Build request body ----
BODY=$(jq -n \
  --argjson tools "$ENABLED_TOOLS_JSON" \
  --arg transport "$TRANSPORT" \
  '{enabledTools: $tools, transport: $transport}')

# ---- Endpoint (control plane) ----
HOST="agentrun.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/2025-09-10/templates/${TEMPLATE_NAME}/mcp/activate"

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method PATCH \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

curl -sS -X PATCH "https://${HOST}${PATH_PART}" \
  -H "Content-Type: application/json" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" \
  -d "$BODY" | jq .

# Post-execution: test the MCP health tool to confirm activation.
