#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    BackupSandboxFiles (Stability Pillar)
# HTTP Method:  GET (list) + GET (download, loop)
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/filesystem
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Backup Sandbox Files
#
# Stability Pillar: 备份沙箱文件以备恢复。建议在 destructive 操作前执行。

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
LIST_PATH="${LIST_PATH:-/workspace}"
LIST_DEPTH="${LIST_DEPTH:-2}"
BACKUP_DIR="${BACKUP_DIR:-./backup-${SANDBOX_ID}-$(date +%Y%m%d%H%M%S)}"
MAX_FILES="${MAX_FILES:-200}"

HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"

# Helper: send a signed GET (with optional --data for empty body).
signed_get() {
  local path="$1" query="$2" outfile="${3:-}"
  local query_args=()
  [ -n "$query" ] && query_args+=( --query "$query" )
  local h=()
  while IFS= read -r line; do
    [ -n "$line" ] && h+=( -H "$line" )
  done < <(python3 "$SIGNER" \
    --method GET \
    --host "$HOST" \
    --path "$path" \
    --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
    --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
    --region "$ALIBABA_CLOUD_REGION_ID" \
    "${query_args[@]}" \
    ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})
  local args=( -sS -X GET "https://${HOST}${path}${query:+?$query}" \
    -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
    "${h[@]}" )
  if [ -n "$outfile" ]; then
    args+=( -o "$outfile" )
  fi
  curl "${args[@]}"
}

mkdir -p "$BACKUP_DIR"

# ---- Step 1: list files ----
echo "→ Listing ${LIST_PATH} (depth=${LIST_DEPTH}) ..."
LISTING=$(signed_get "/sandboxes/${SANDBOX_ID}/filesystem" "path=${LIST_PATH}&depth=${LIST_DEPTH}")
echo "$LISTING" | jq .

# Extract file paths via jq; bail out if nothing matched.
mapfile -t FILES < <(echo "$LISTING" | jq -r '.entries[]? | select(.type=="file") | .path')
if [ "${#FILES[@]}" -eq 0 ]; then
  echo "No files found under ${LIST_PATH}; nothing to back up." >&2
  exit 0
fi
if [ "${#FILES[@]}" -gt "$MAX_FILES" ]; then
  echo "ERROR: ${#FILES[@]} files exceed MAX_FILES=${MAX_FILES}; bump MAX_FILES or narrow LIST_PATH." >&2
  exit 65
fi

# ---- Step 2: download each file ----
echo "→ Downloading ${#FILES[@]} files to ${BACKUP_DIR} ..."
for file in "${FILES[@]}"; do
  rel="${file#/}"  # strip leading /
  dest="${BACKUP_DIR}/${rel}"
  mkdir -p "$(dirname "$dest")"
  printf '  %s\n' "$file"
  signed_get "/sandboxes/${SANDBOX_ID}/filesystem/download" "path=${file}" "$dest"
done

# Post-execution: verify file count + sizes match listing.
echo "→ Backup complete: $(find "$BACKUP_DIR" -type f | wc -l | tr -d ' ') files in ${BACKUP_DIR}"
