#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    CreateTemplate
# HTTP Method:  POST
# Endpoint:     https://agentrun.${REGION}.aliyuncs.com/2025-09-10/templates
# Plane:        control
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Create Template

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
TEMPLATE_NAME="${TEMPLATE_NAME:-my-template}"
DESCRIPTION="${DESCRIPTION:-Created by alicloud-agentrun-ops code-snippets}"
TEMPLATE_TYPE="${TEMPLATE_TYPE:-CodeInterpreter}"
CPU="${CPU:-2}"
MEMORY="${MEMORY:-4096}"
DISK_SIZE="${DISK_SIZE:-10240}"
IDLE_TIMEOUT="${IDLE_TIMEOUT:-1800}"
NETWORK_MODE="${NETWORK_MODE:-PUBLIC}"

# Optional: set VPC_* and SECURITY_GROUP_ID / VSWITCH_ID to enable PRIVATE mode
VPC_ID="${VPC_ID:-}"
SECURITY_GROUP_ID="${SECURITY_GROUP_ID:-}"
VSWITCH_ID="${VSWITCH_ID:-}"

# ---- Build request body ----
if [ "$NETWORK_MODE" = "PRIVATE" ]; then
  : "${VPC_ID:?PRIVATE mode requires VPC_ID}"
  : "${SECURITY_GROUP_ID:?PRIVATE mode requires SECURITY_GROUP_ID}"
  : "${VSWITCH_ID:?PRIVATE mode requires VSWITCH_ID}"
  BODY=$(jq -n \
    --arg name "$TEMPLATE_NAME" \
    --arg desc "$DESCRIPTION" \
    --arg type "$TEMPLATE_TYPE" \
    --argjson cpu "$CPU" \
    --argjson memory "$MEMORY" \
    --argjson disk "$DISK_SIZE" \
    --argjson idle "$IDLE_TIMEOUT" \
    --arg vpc "$VPC_ID" \
    --arg sg "$SECURITY_GROUP_ID" \
    --arg vsw "$VSWITCH_ID" \
    '{
      templateName: $name,
      description: $desc,
      templateType: $type,
      cpu: $cpu,
      memory: $memory,
      diskSize: $disk,
      sandboxIdleTimeoutInSeconds: $idle,
      networkConfiguration: {
        networkMode: "PRIVATE",
        vpcId: $vpc,
        securityGroupId: $sg,
        vSwitchId: $vsw
      }
    }')
else
  BODY=$(jq -n \
    --arg name "$TEMPLATE_NAME" \
    --arg desc "$DESCRIPTION" \
    --arg type "$TEMPLATE_TYPE" \
    --argjson cpu "$CPU" \
    --argjson memory "$MEMORY" \
    --argjson disk "$DISK_SIZE" \
    --argjson idle "$IDLE_TIMEOUT" \
    '{
      templateName: $name,
      description: $desc,
      templateType: $type,
      cpu: $cpu,
      memory: $memory,
      diskSize: $disk,
      sandboxIdleTimeoutInSeconds: $idle,
      networkConfiguration: { networkMode: "PUBLIC" }
    }')
fi

# ---- Endpoint (control plane) ----
HOST="agentrun.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/2025-09-10/templates"

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method POST \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

curl -sS -X POST "https://${HOST}${PATH_PART}" \
  -H "Content-Type: application/json" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" \
  -d "$BODY" | jq .

# Response hints:
#   $.templateId  -> new template ID
#   $.status      -> READY (poll GetTemplate if != READY)
