#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    DeepHibernation (Pause / Resume Session)
# HTTP Method:  POST
# Endpoint:     https://agentrun.${REGION}.aliyuncs.com/2025-09-10/sandboxes/${SANDBOX_ID}/{pause|resume}
# Plane:        control
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Deep Hibernation (Pause/Resume Session)
#
# Sub-operation is selected via HIBERNATION_ACTION env var:
#   HIBERNATION_ACTION=pause                       -> POST /pause   (releases compute, keeps files)
#   HIBERNATION_ACTION=resume                      -> POST /resume  (re-allocates compute, restores state)
#   HIBERNATION_ACTION=resume_fs_only              -> POST /resume  with {"fileSystemOnly": true}
#                                                   (faster, cheaper, but contexts lost)
# Default: HIBERNATION_ACTION=pause.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
HIBERNATION_ACTION="${HIBERNATION_ACTION:-pause}"

# ---- Dispatch ----
HOST="agentrun.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"

case "$HIBERNATION_ACTION" in
  pause)
    METHOD="POST"
    PATH_PART="/2025-09-10/sandboxes/${SANDBOX_ID}/pause"
    BODY='{}'
    ;;
  resume)
    METHOD="POST"
    PATH_PART="/2025-09-10/sandboxes/${SANDBOX_ID}/resume"
    BODY='{}'
    ;;
  resume_fs_only)
    METHOD="POST"
    PATH_PART="/2025-09-10/sandboxes/${SANDBOX_ID}/resume"
    BODY='{"fileSystemOnly": true}'
    ;;
  *)
    echo "ERROR: HIBERNATION_ACTION must be one of: pause | resume | resume_fs_only" >&2
    exit 2
    ;;
esac

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method "$METHOD" \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

curl -sS -X POST "https://${HOST}${PATH_PART}" \
  -H "Content-Type: application/json" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" \
  -d "$BODY" | jq .

# State machine:
#   READY -(pause)-> HIBERNATED -(resume)-> READY
# After resume, poll GetSandbox until status=READY (interval 5s, max 120s).
