#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    DeleteTemplate (Safety Gate)
# HTTP Method:  GET (list dependents) + DELETE
# Endpoint:     https://agentrun.${REGION}.aliyuncs.com/2025-09-10/templates/${TEMPLATE_NAME}
# Plane:        control
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Delete Template (Safety Gate)
#
# DESTRUCTIVE: cannot create new sandboxes from this template after deletion.
# Set CONFIRM=yes AND FORCE=yes to skip the dependent-sandboxes pre-check.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${TEMPLATE_NAME:?missing TEMPLATE_NAME}"
FORCE="${FORCE:-no}"

HOST="agentrun.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"

# Helper: send a signed request and pretty-print the response.
signed_curl() {
  local method="$1" path="$2" body="${3:-}"
  local h=()
  while IFS= read -r line; do
    [ -n "$line" ] && h+=( -H "$line" )
  done < <(python3 "$SIGNER" \
    --method "$method" \
    --host "$HOST" \
    --path "$path" \
    --body "$body" \
    --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
    --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
    --region "$ALIBABA_CLOUD_REGION_ID" \
    ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})
  local args=( -sS -X "$method" "https://${HOST}${path}" \
    -H "Content-Type: application/json" \
    -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
    "${h[@]}" )
  [ -n "$body" ] && args+=( -d "$body" )
  curl "${args[@]}" | jq .
}

# ---- Step 1: list dependent sandboxes ----
echo "→ Checking for dependent sandboxes (templateName=${TEMPLATE_NAME}) ..."
DEPS=$(signed_curl GET "/2025-09-10/sandboxes?templateName=${TEMPLATE_NAME}&status=READY")
COUNT=$(echo "$DEPS" | jq -r '.data.items | length // 0')
if [ "$COUNT" -gt 0 ] && [ "$FORCE" != "yes" ]; then
  echo "ERROR: ${COUNT} active sandboxes depend on template ${TEMPLATE_NAME}." >&2
  echo "       Stop and delete them first, or set FORCE=yes to override." >&2
  exit 66
fi
if [ "$COUNT" -gt 0 ]; then
  echo "WARNING: ${COUNT} active sandboxes still exist (FORCE=yes; proceeding)" >&2
fi

# ---- Safety gate ----
if [ "${CONFIRM:-no}" != "yes" ]; then
  echo "ERROR: DeleteTemplate is irreversible. Set CONFIRM=yes to proceed." >&2
  exit 64
fi

# ---- Step 2: delete ----
echo "→ Deleting template ${TEMPLATE_NAME} ..."
signed_curl DELETE "/2025-09-10/templates/${TEMPLATE_NAME}"

# Post-execution: GetTemplate should return 404.
