#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    DeleteSandbox (Safety Gate)
# HTTP Method:  POST /stop  +  DELETE
# Endpoint:     https://agentrun.${REGION}.aliyuncs.com/2025-09-10/sandboxes/${SANDBOX_ID}
# Plane:        control
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Delete Sandbox (Safety Gate)
#
# DESTRUCTIVE: irreversibly destroys sandbox state, files, and contexts.
# Set CONFIRM=yes to acknowledge.

set -euo pipefail

# ---- Safety gate ----
if [ "${CONFIRM:-no}" != "yes" ]; then
  echo "ERROR: DeleteSandbox is irreversible. Set CONFIRM=yes to proceed." >&2
  echo "       (This will stop then delete sandbox ${SANDBOX_ID:-<unset>}.)" >&2
  exit 64
fi

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
# Set SKIP_STOP=yes to skip the stop step (e.g. sandbox already TERMINATED).
SKIP_STOP="${SKIP_STOP:-no}"

HOST="agentrun.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"

# Helper: send a signed request and pretty-print the response.
signed_curl() {
  local method="$1" path="$2" body="${3:-}"
  local args=( -sS -X "$method" "https://${HOST}${path}" \
    -H "Content-Type: application/json" \
    -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" )
  local h=()
  while IFS= read -r line; do
    [ -n "$line" ] && h+=( -H "$line" )
  done < <(python3 "$SIGNER" \
    --method "$method" \
    --host "$HOST" \
    --path "$path" \
    --body "$body" \
    --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
    --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
    --region "$ALIBABA_CLOUD_REGION_ID" \
    ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})
  args+=( "${h[@]}" )
  if [ -n "$body" ]; then
    args+=( -d "$body" )
  fi
  curl "${args[@]}" | jq .
}

# ---- Step 1: stop (idempotent; safe to retry) ----
if [ "$SKIP_STOP" != "yes" ]; then
  echo "→ Stopping sandbox ${SANDBOX_ID} ..."
  signed_curl POST "/2025-09-10/sandboxes/${SANDBOX_ID}/stop" '{}' || true
fi

# ---- Step 2: delete ----
echo "→ Deleting sandbox ${SANDBOX_ID} ..."
signed_curl DELETE "/2025-09-10/sandboxes/${SANDBOX_ID}"

# Post-execution: poll GetSandbox until 404 or status=TERMINATED (interval 5s, max 60s).
