#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    ExecuteCode (in sandbox)
# HTTP Method:  POST
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/contexts/execute
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Execute Code in Sandbox

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
LANGUAGE="${LANGUAGE:-python}"
CODE="${CODE:-print('hello from agentrun')}"
TIMEOUT="${TIMEOUT:-30}"

# ---- Build request body ----
BODY=$(jq -n \
  --arg lang "$LANGUAGE" \
  --arg code "$CODE" \
  --argjson t "$TIMEOUT" \
  '{language: $lang, code: $code, timeout: $t}')

# ---- Endpoint (data plane — note the {account} subdomain) ----
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/sandboxes/${SANDBOX_ID}/contexts/execute"

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method POST \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

curl -sS -X POST "https://${HOST}${PATH_PART}" \
  -H "Content-Type: application/json" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" \
  -d "$BODY" | jq .

# Response hints:
#   $.results[type=stdout].text   -> stdout
#   $.results[type=stderr].text   -> stderr
#   $.results[type=result].text   -> return value
#   $.results[type=endOfExecution].status  -> ok | error | timeout
