#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    ExecuteCommand (Safety Gate)
# HTTP Method:  POST
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/processes/cmd
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Execute Command in Sandbox
#
# SAFETY GATE: command is checked against critical dangerous patterns
# (e.g. "rm -rf /", "curl|bash").  See references/security-enhancement.md §3.2.
# Set CONFIRM=yes to bypass the soft warn for medium-risk patterns.
# Hard blocks (critical patterns) always HALT regardless of CONFIRM.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
: "${COMMAND:?missing COMMAND}"
CWD="${CWD:-/home/user}"

# ---- Safety gate: critical patterns always HALT ----
if echo "$COMMAND" | grep -Eq '(^|[[:space:]])rm[[:space:]]+-rf?[[:space:]]+/([[:space:]]|$)|curl[[:space:]]+[^|]*\|[[:space:]]*bash|:(){\s*:\|:&amp;\s*};:'; then
  echo "ERROR: command matches a CRITICAL dangerous pattern; refusing to execute." >&2
  echo "       (rm -rf /, curl|bash, fork-bomb, etc.)" >&2
  exit 68
fi
# Soft warn for medium-risk patterns unless explicitly confirmed.
if echo "$COMMAND" | grep -Eq '(^|[[:space:]])(sudo|chmod[[:space:]]+777|dd[[:space:]]+if=|mkfs|shutdown|reboot)([[:space:]]|$)'; then
  if [ "${CONFIRM:-no}" != "yes" ]; then
    echo "WARNING: command matches a medium-risk pattern (sudo / chmod 777 / dd / mkfs / shutdown / reboot)." >&2
    echo "         Set CONFIRM=yes to proceed." >&2
    exit 69
  fi
fi

# ---- Build request body ----
BODY=$(jq -n --arg cmd "$COMMAND" --arg cwd "$CWD" '{command: $cmd, cwd: $cwd}')

# ---- Endpoint (data plane) ----
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/sandboxes/${SANDBOX_ID}/processes/cmd"

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method POST \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

curl -sS -X POST "https://${HOST}${PATH_PART}" \
  -H "Content-Type: application/json" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" \
  -d "$BODY" | jq .

# Response hints:
#   $.executionId
#   $.result.exitCode   (0 = success)
#   $.result.stdout
#   $.result.stderr
# Hard timeout: 30s enforced by data-plane gateway.
