#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    FileSystemOperations (read / write / list / download /
#                                      upload / mkdir / move / remove)
# HTTP Method:  GET / POST / DELETE (per sub-op)
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/files[?path=...]
#               https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/filesystem/...
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: File System Operations
#
# Sub-operation is selected via FS_ACTION env var:
#   FS_ACTION=read      -> GET    /sandboxes/{id}/files?path=PATH
#   FS_ACTION=write     -> POST   /sandboxes/{id}/files          (body: path, content, encoding)
#   FS_ACTION=list      -> GET    /sandboxes/{id}/filesystem?path=PATH&depth=DEPTH
#   FS_ACTION=download  -> GET    /sandboxes/{id}/filesystem/download?path=PATH  (output to LOCAL_DEST)
#   FS_ACTION=upload    -> POST   /sandboxes/{id}/filesystem/upload  (multipart; source=LOCAL_FILE, target=path)
#   FS_ACTION=mkdir     -> POST   /sandboxes/{id}/filesystem/mkdir  (body: path)
#   FS_ACTION=move      -> POST   /sandboxes/{id}/filesystem/move   (body: source, destination)
#   FS_ACTION=remove    -> POST   /sandboxes/{id}/filesystem/remove (body: path)  [SAFETY GATE]
# Default: FS_ACTION=read.
#
# Path safety: this script refuses paths containing '..' or starting with '.'.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
FS_ACTION="${FS_ACTION:-read}"
PATH_PARAM="${PATH_PARAM:-/workspace}"
DEPTH="${DEPTH:-2}"
FILE_CONTENT="${FILE_CONTENT:-}"
ENCODING="${ENCODING:-utf-8}"
SOURCE_PATH="${SOURCE_PATH:-}"
DEST_PATH="${DEST_PATH:-}"
LOCAL_FILE="${LOCAL_FILE:-}"
LOCAL_DEST="${LOCAL_DEST:-./download.bin}"

assert_safe_path() {
  case "$1" in
    *..*)  echo "ERROR: path contains '..': $1" >&2; exit 67 ;;
    .*)    echo "ERROR: hidden path rejected: $1" >&2; exit 67 ;;
    /*)    : ;;  # leading slash is fine (absolute)
    *)     : ;;  # relative path is fine
  esac
}

# ---- Dispatch: METHOD / PATH / BODY / query ----
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
QUERY=""
BODY=""
OUTFILE=""

case "$FS_ACTION" in
  read)
    assert_safe_path "$PATH_PARAM"
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/files"
    QUERY="path=${PATH_PARAM}"
    ;;
  write)
    assert_safe_path "$PATH_PARAM"
    METHOD="POST"
    PATH_PART="/sandboxes/${SANDBOX_ID}/files"
    BODY=$(jq -n --arg p "$PATH_PARAM" --arg c "$FILE_CONTENT" --arg e "$ENCODING" \
      '{path: $p, content: $c, encoding: $e}')
    ;;
  list)
    assert_safe_path "$PATH_PARAM"
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem"
    QUERY="depth=${DEPTH}&path=${PATH_PARAM}"
    ;;
  download)
    assert_safe_path "$PATH_PARAM"
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem/download"
    QUERY="path=${PATH_PARAM}"
    OUTFILE="$LOCAL_DEST"
    ;;
  upload)
    : "${LOCAL_FILE:?FS_ACTION=upload requires LOCAL_FILE}"
    assert_safe_path "$PATH_PARAM"
    METHOD="POST"
    PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem/upload"
    # Multipart body is built into a temp file (sign.py reads it via @).
    BOUNDARY="----agentrun-$(date +%s%N)"
    CRLF=$'\r\n'
    {
      printf -- '--%s%s' "$BOUNDARY" "$CRLF"
      printf 'Content-Disposition: form-data; name="path"%s%s' "$CRLF" "$CRLF"
      printf '%s%s' "$PATH_PARAM" "$CRLF"
      printf -- '--%s%s' "$BOUNDARY" "$CRLF"
      printf 'Content-Disposition: form-data; name="file"; filename="%s"%s' "$(basename "$LOCAL_FILE")" "$CRLF"
      printf 'Content-Type: application/octet-stream%s%s' "$CRLF" "$CRLF"
      cat "$LOCAL_FILE"
      printf '%s' "$CRLF"
      printf -- '--%s--%s' "$BOUNDARY" "$CRLF"
    } > /tmp/agentrun-upload.$$.bin
    BODY="@/tmp/agentrun-upload.$$.bin"
    CONTENT_TYPE="multipart/form-data; boundary=${BOUNDARY}"
    trap 'rm -f /tmp/agentrun-upload.$$.bin' EXIT
    ;;
  mkdir)
    assert_safe_path "$PATH_PARAM"
    METHOD="POST"
    PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem/mkdir"
    BODY=$(jq -n --arg p "$PATH_PARAM" '{path: $p}')
    ;;
  move)
    : "${SOURCE_PATH:?FS_ACTION=move requires SOURCE_PATH}"
    : "${DEST_PATH:?FS_ACTION=move requires DEST_PATH}"
    assert_safe_path "$SOURCE_PATH"
    assert_safe_path "$DEST_PATH"
    METHOD="POST"
    PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem/move"
    BODY=$(jq -n --arg s "$SOURCE_PATH" --arg d "$DEST_PATH" \
      '{source: $s, destination: $d}')
    ;;
  remove)
    assert_safe_path "$PATH_PARAM"
    if [ "$PATH_PARAM" = "/" ] || [ -z "$PATH_PARAM" ]; then
      echo "ERROR: refuse to remove root or empty path." >&2; exit 67
    fi
    if [ "${CONFIRM:-no}" != "yes" ]; then
      echo "ERROR: FS_ACTION=remove is destructive. Set CONFIRM=yes to proceed." >&2
      exit 64
    fi
    METHOD="POST"
    PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem/remove"
    BODY=$(jq -n --arg p "$PATH_PARAM" '{path: $p}')
    ;;
  *)
    echo "ERROR: FS_ACTION must be one of: read | write | list | download | upload | mkdir | move | remove" >&2
    exit 2
    ;;
esac

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
SIGN_ARGS=(
  --method "$METHOD"
  --host "$HOST"
  --path "$PATH_PART"
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID"
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET"
  --region "$ALIBABA_CLOUD_REGION_ID"
)
[ -n "$QUERY" ]      && SIGN_ARGS+=( --query "$QUERY" )
[ -n "${CONTENT_TYPE:-}" ] && SIGN_ARGS+=( --content-type "$CONTENT_TYPE" )
if [ -n "$BODY" ] && [ "$BODY" = "@/tmp/"* ]; then
  # Body read from file (multipart upload).
  SIGN_ARGS+=( --body "$BODY" )
elif [ -n "$BODY" ]; then
  SIGN_ARGS+=( --body "$BODY" )
fi
[ -n "${ALIBABA_CLOUD_SECURITY_TOKEN:-}" ] && SIGN_ARGS+=( --session-token "$ALIBABA_CLOUD_SECURITY_TOKEN" )

HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" "${SIGN_ARGS[@]}")

CURL_ARGS=( -sS -X "$METHOD" "https://${HOST}${PATH_PART}${QUERY:+?$QUERY}" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" )
if [ "$FS_ACTION" = "upload" ]; then
  # curl --data-binary @file preserves the exact multipart body we built.
  CURL_ARGS+=( --data-binary "@/tmp/agentrun-upload.$$.bin" )
elif [ -n "$BODY" ]; then
  CURL_ARGS+=( -d "$BODY" )
fi
[ -n "$OUTFILE" ] && CURL_ARGS+=( -o "$OUTFILE" )

curl "${CURL_ARGS[@]}" | jq .
