#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    HealthCheck
# HTTP Method:  GET
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/health
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Health Check
#
# Expected response: {"status":"ok","service":"sandbox-code-interpreter","version":"v1"}

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"

# ---- Endpoint (data plane) ----
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/sandboxes/${SANDBOX_ID}/health"

# ---- Sign + send (no body, no query) ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method GET \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

RESP=$(curl -sS -X GET "https://${HOST}${PATH_PART}" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}")
echo "$RESP" | jq .

# Exit non-zero if status != ok (for use in shell pipelines / readiness probes).
STATUS=$(echo "$RESP" | jq -r '.status // "unknown"')
if [ "$STATUS" != "ok" ]; then
  echo "ERROR: sandbox health status is '${STATUS}'" >&2
  exit 70
fi
