#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    ListResources (Pagination) — ListTemplates / ListSandboxes
# HTTP Method:  GET
# Endpoint:     https://agentrun.${REGION}.aliyuncs.com/2025-09-10/templates[?...&nextToken=...]
#               https://agentrun.${REGION}.aliyuncs.com/2025-09-10/sandboxes[?maxResults=...&nextToken=...]
# Plane:        control
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: List Resources (Pagination)
#
# Resource is selected via LIST_RESOURCE env var:
#   LIST_RESOURCE=templates -> ListTemplates  (pageSize / pageNumber / status)
#   LIST_RESOURCE=sandboxes -> ListSandboxes  (maxResults / nextToken / status)
# Default: LIST_RESOURCE=templates.
#
# Pagination:
#   - templates uses pageSize + pageNumber; iterate while items is non-empty.
#   - sandboxes uses maxResults + nextToken cursor; iterate while nextToken != "".
# Use LIST_ALL=yes to follow the cursor and emit every item on stdout (one
# JSON object per line) — useful for piping into jq.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
LIST_RESOURCE="${LIST_RESOURCE:-templates}"
STATUS_FILTER="${STATUS_FILTER:-READY}"
PAGE_SIZE="${PAGE_SIZE:-20}"
MAX_RESULTS="${MAX_RESULTS:-100}"
LIST_ALL="${LIST_ALL:-no}"

HOST="agentrun.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"

signed_get_with_query() {
  local path="$1" query="$2"
  local h=()
  while IFS= read -r line; do
    [ -n "$line" ] && h+=( -H "$line" )
  done < <(python3 "$SIGNER" \
    --method GET \
    --host "$HOST" \
    --path "$path" \
    --query "$query" \
    --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
    --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
    --region "$ALIBABA_CLOUD_REGION_ID" \
    ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})
  curl -sS -X GET "https://${HOST}${path}?${query}" \
    -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
    "${h[@]}"
}

case "$LIST_RESOURCE" in
  templates)
    if [ "$LIST_ALL" = "yes" ]; then
      # Page-number pagination.
      page=1
      while :; do
        QUERY="pageNumber=${page}&pageSize=${PAGE_SIZE}&status=${STATUS_FILTER}"
        RESP=$(signed_get_with_query "/2025-09-10/templates" "$QUERY")
        ITEMS=$(echo "$RESP" | jq -c '.templates[]? // empty')
        [ -z "$ITEMS" ] && break
        echo "$ITEMS"
        page=$((page + 1))
      done
    else
      # Single page.
      QUERY="pageNumber=1&pageSize=${PAGE_SIZE}&status=${STATUS_FILTER}"
      signed_get_with_query "/2025-09-10/templates" "$QUERY" | jq .
    fi
    ;;
  sandboxes)
    if [ "$LIST_ALL" = "yes" ]; then
      # Cursor pagination.
      next_token=""
      while :; do
        # Build query: nextToken must be present (empty allowed on first call).
        QUERY="maxResults=${MAX_RESULTS}&nextToken=${next_token}&status=${STATUS_FILTER}"
        RESP=$(signed_get_with_query "/2025-09-10/sandboxes" "$QUERY")
        ITEMS=$(echo "$RESP" | jq -c '.data.items[]? // empty')
        [ -z "$ITEMS" ] && break
        echo "$ITEMS"
        next_token=$(echo "$RESP" | jq -r '.data.nextToken // ""')
        [ -z "$next_token" ] && break
      done
    else
      QUERY="maxResults=${MAX_RESULTS}&nextToken=&status=${STATUS_FILTER}"
      signed_get_with_query "/2025-09-10/sandboxes" "$QUERY" | jq .
    fi
    ;;
  *)
    echo "ERROR: LIST_RESOURCE must be one of: templates | sandboxes" >&2
    exit 2
    ;;
esac
