#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    ManageExecutionContexts (Create / List / Get / Delete)
# HTTP Method:  POST (create) / GET (list, get) / DELETE
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/contexts[/{CONTEXT_ID}]
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Manage Execution Contexts
#
# Sub-operation is selected via ACTION env var:
#   ACTION=create   -> POST   /sandboxes/{id}/contexts
#   ACTION=list     -> GET    /sandboxes/{id}/contexts
#   ACTION=get      -> GET    /sandboxes/{id}/contexts/{ctx_id}
#   ACTION=delete   -> DELETE /sandboxes/{id}/contexts/{ctx_id}
# Default: ACTION=create.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
ACTION="${ACTION:-create}"
LANGUAGE="${LANGUAGE:-python}"
CWD="${CWD:-/home/user}"
CONTEXT_ID="${CONTEXT_ID:-}"

# ---- Dispatch: HTTP method + path + body ----
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"

case "$ACTION" in
  create)
    METHOD="POST"
    PATH_PART="/sandboxes/${SANDBOX_ID}/contexts"
    BODY=$(jq -n --arg lang "$LANGUAGE" --arg cwd "$CWD" \
      '{language: $lang, cwd: $cwd}')
    ;;
  list)
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/contexts"
    BODY=""
    ;;
  get)
    : "${CONTEXT_ID:?ACTION=get requires CONTEXT_ID}"
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/contexts/${CONTEXT_ID}"
    BODY=""
    ;;
  delete)
    : "${CONTEXT_ID:?ACTION=delete requires CONTEXT_ID}"
    METHOD="DELETE"
    PATH_PART="/sandboxes/${SANDBOX_ID}/contexts/${CONTEXT_ID}"
    BODY=""
    ;;
  *)
    echo "ERROR: ACTION must be one of: create | list | get | delete" >&2
    exit 2
    ;;
esac

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method "$METHOD" \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

CURL_ARGS=( -sS -X "$METHOD" "https://${HOST}${PATH_PART}" \
  -H "Content-Type: application/json" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" )
[ -n "$BODY" ] && CURL_ARGS+=( -d "$BODY" )

curl "${CURL_ARGS[@]}" | jq .

# Response hints:
#   create -> $.id (new context id)
#   list   -> $.contexts[] (array of contexts)
