#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    ProcessManagement (List / Kill)
# HTTP Method:  GET (list) / DELETE (kill)
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/processes[/{PID}]
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Process Management
#
# Sub-operation is selected via PROCESS_ACTION env var:
#   PROCESS_ACTION=list  -> GET    /sandboxes/{id}/processes
#   PROCESS_ACTION=kill  -> DELETE /sandboxes/{id}/processes/{pid}    [SAFETY GATE]
#   PROCESS_ACTION=stat  -> GET    /sandboxes/{id}/processes/{pid}    (PID details)
# Default: PROCESS_ACTION=list.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
PROCESS_ACTION="${PROCESS_ACTION:-list}"
PID="${PID:-}"

# ---- Dispatch ----
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"

case "$PROCESS_ACTION" in
  list)
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/processes"
    BODY=""
    ;;
  stat)
    : "${PID:?PROCESS_ACTION=stat requires PID}"
    METHOD="GET"
    PATH_PART="/sandboxes/${SANDBOX_ID}/processes/${PID}"
    BODY=""
    ;;
  kill)
    : "${PID:?PROCESS_ACTION=kill requires PID}"
    if [ "${CONFIRM:-no}" != "yes" ]; then
      echo "ERROR: kill sends SIGTERM then SIGKILL. Set CONFIRM=yes to proceed." >&2
      echo "       (target: PID ${PID} in sandbox ${SANDBOX_ID})" >&2
      exit 64
    fi
    METHOD="DELETE"
    PATH_PART="/sandboxes/${SANDBOX_ID}/processes/${PID}"
    BODY=""
    ;;
  *)
    echo "ERROR: PROCESS_ACTION must be one of: list | stat | kill" >&2
    exit 2
    ;;
esac

# ---- Sign + send ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
HEADERS=()
while IFS= read -r line; do
  [ -n "$line" ] && HEADERS+=( -H "$line" )
done < <(python3 "$SIGNER" \
  --method "$METHOD" \
  --host "$HOST" \
  --path "$PATH_PART" \
  --body "$BODY" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

CURL_ARGS=( -sS -X "$METHOD" "https://${HOST}${PATH_PART}" \
  -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
  "${HEADERS[@]}" )
[ -n "$BODY" ] && CURL_ARGS+=( -d "$BODY" )

curl "${CURL_ARGS[@]}" | jq .
