#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    RestoreFilesToSandbox (Stability Pillar)
# HTTP Method:  POST (multipart upload, loop)
# Endpoint:     https://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/filesystem/upload
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: Restore Files to Sandbox
#
# Stability Pillar: emergency recovery from a previous backup (see
# backup_files.sh). Set CONFIRM=yes to acknowledge that existing files
# at the same target path will be overwritten.
#
# Each file in BACKUP_DIR is uploaded under its relative path inside the
# sandbox at SANDBOX_TARGET_ROOT (default /workspace). Max 100 MB per file.

set -euo pipefail

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"
: "${BACKUP_DIR:?missing BACKUP_DIR — directory produced by backup_files.sh}"
SANDBOX_TARGET_ROOT="${SANDBOX_TARGET_ROOT:-/workspace}"
MAX_BYTES="${MAX_BYTES:-104857600}"  # 100 MB per file (server limit)
CONFIRM="${CONFIRM:-no}"

if [ "$CONFIRM" != "yes" ]; then
  echo "ERROR: restore will overwrite existing files at ${SANDBOX_TARGET_ROOT}/..." >&2
  echo "       Set CONFIRM=yes to proceed." >&2
  exit 64
fi
if [ ! -d "$BACKUP_DIR" ]; then
  echo "ERROR: BACKUP_DIR does not exist: $BACKUP_DIR" >&2
  exit 71
fi

HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/sandboxes/${SANDBOX_ID}/filesystem/upload"
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"

upload_file() {
  local src="$1" rel="$2"
  local size
  size=$(stat -c%s "$src" 2>/dev/null || stat -f%z "$src")
  if [ "$size" -gt "$MAX_BYTES" ]; then
    echo "SKIP: $rel (${size} bytes exceeds ${MAX_BYTES})" >&2
    return 0
  fi
  local BOUNDARY="----agentrun-restore-$$-$(date +%s%N)"
  local CRLF=$'\r\n'
  local body_file
  body_file=$(mktemp -t agentrun-restore.XXXXXX.bin)
  {
    printf -- '--%s%s' "$BOUNDARY" "$CRLF"
    printf 'Content-Disposition: form-data; name="path"%s%s' "$CRLF" "$CRLF"
    printf '%s/%s%s' "${SANDBOX_TARGET_ROOT%/}" "$rel" "$CRLF"
    printf -- '--%s%s' "$BOUNDARY" "$CRLF"
    printf 'Content-Disposition: form-data; name="file"; filename="%s"%s' "$(basename "$rel")" "$CRLF"
    printf 'Content-Type: application/octet-stream%s%s' "$CRLF" "$CRLF"
    cat "$src"
    printf '%s' "$CRLF"
    printf -- '--%s--%s' "$BOUNDARY" "$CRLF"
  } > "$body_file"

  local h=()
  while IFS= read -r line; do
    [ -n "$line" ] && h+=( -H "$line" )
  done < <(python3 "$SIGNER" \
    --method POST \
    --host "$HOST" \
    --path "$PATH_PART" \
    --body "@${body_file}" \
    --content-type "multipart/form-data; boundary=${BOUNDARY}" \
    --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
    --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
    --region "$ALIBABA_CLOUD_REGION_ID" \
    ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"})

  curl -sS -X POST "https://${HOST}${PATH_PART}" \
    -H "X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}" \
    "${h[@]}" \
    --data-binary "@${body_file}" \
    | jq -c '.'
  rm -f "$body_file"
  printf '  %s\n' "$rel"
}

# Walk BACKUP_DIR and upload each file preserving the relative path.
count=0
while IFS= read -r -d '' src; do
  rel="${src#${BACKUP_DIR}/}"
  upload_file "$src" "$rel"
  count=$((count + 1))
done < <(find "$BACKUP_DIR" -type f -print0)

echo "→ Restored ${count} file(s) to sandbox ${SANDBOX_ID} under ${SANDBOX_TARGET_ROOT}"

# Post-execution: use ExecuteCode to run a small test that verifies a
# sample restored file is readable; or use ListFiles + size comparison.
