#!/usr/bin/env python3
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# sign.py — ACS3-HMAC-SHA256 签名工具 (Alibaba Cloud AgentRun)
#
# Why a separate helper?
#   AgentRun has NO official CLI or SDK. Every operation must be a direct HTTP
#   call to `agentrun.{region}.aliyuncs.com` (control plane) or
#   `{account}.agentrun-data.{region}.aliyuncs.com` (data plane) with an
#   ACS3-HMAC-SHA256 Authorization header. Centralising the signature logic in
#   one module keeps every shell snippet thin and consistent.
#
# Reference: alicloud-agentrun-ops/references/api-signing.md §3
#
# Usage (CLI, for shell snippets):
#     python3 sign.py \
#         --method POST \
#         --host agentrun.cn-hangzhou.aliyuncs.com \
#         --path /2025-09-10/templates \
#         --body '{"templateName":"my-tpl","cpu":2,"memory":4096}' \
#         --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
#         --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
#         --region cn-hangzhou
#
# For GET-with-query, pass --query "path=/foo&depth=2" (no leading '?').
#
# Output: one "Header-Name: value" line per signed header on stdout. Shell
# scripts consume the output via:
#     while IFS= read -r line; do args+=( -H "$line" ); done < <(python3 sign.py ...)

from __future__ import annotations

import argparse
import datetime
import hashlib
import hmac
import sys
from pathlib import Path
from urllib.parse import quote as _urllib_quote

# Headers that always participate in the signature. Aligned with
# references/api-signing.md §2.1 — adding extra headers here is a
# breaking change because the server validates the signed set.
_SIGNED_HEADERS: tuple[tuple[str, str], ...] = (
    ("content-type", "application/json"),
    ("host", ""),  # filled in per-request
    ("x-acs-content-sha256", ""),  # filled in per-request
    ("x-acs-date", ""),  # filled in per-request
)


def _canonical_query_string(query: str) -> str:
    """Return a sorted, URL-encoded canonical query string.

    AgentRun signing requires the canonical request to embed the query
    string with each parameter URI-encoded twice (RFC 3986 strict), then
    sorted by encoded name and value. An empty input yields "".
    """
    if not query:
        return ""
    pairs: list[tuple[str, str]] = []
    for raw in query.split("&"):
        if not raw:
            continue
        if "=" in raw:
            k, v = raw.split("=", 1)
        else:
            k, v = raw, ""
        # Encode twice per ACS3 spec: 1) parse 2) canonical.
        enc_k = _urllib_quote(k, safe="-_.~")
        enc_v = _urllib_quote(v, safe="-_.~")
        pairs.append((enc_k, enc_v))
    pairs.sort()
    return "&".join(f"{k}={v}" for k, v in pairs)


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _hmac_sha256(key: bytes, data: str) -> bytes:
    return hmac.new(key, data.encode("utf-8"), hashlib.sha256).digest()


def _derive_signing_key(secret: str, date: str, region: str, service: str) -> bytes:
    k_secret = ("ACS3" + secret).encode("utf-8")
    k_date = _hmac_sha256(k_secret, date)
    k_region = _hmac_sha256(k_date, region)
    k_service = _hmac_sha256(k_region, service)
    return _hmac_sha256(k_service, "aliyun_v4_request")


def _read_body(body_arg: str) -> bytes:
    """Resolve a `--body` argument.

    `"@/path/to/file"` reads the file as bytes (used for multipart uploads
    where the body cannot be expressed inline). An empty string yields b"".
    Everything else is encoded as UTF-8.
    """
    if not body_arg:
        return b""
    if body_arg.startswith("@"):
        return Path(body_arg[1:]).read_bytes()
    return body_arg.encode("utf-8")


def sign(
    method: str,
    host: str,
    path: str,
    body: str,
    ak: str,
    sk: str,
    region: str,
    *,
    service: str = "agentrun",
    content_type: str = "application/json",
    query: str = "",
    session_token: str | None = None,
) -> dict[str, str]:
    """Build ACS3-HMAC-SHA256 signed headers for an AgentRun request.

    Args:
        method: HTTP verb in any case (POST/GET/PUT/PATCH/DELETE).
        host: Endpoint host without scheme, e.g. `agentrun.cn-hangzhou.aliyuncs.com`.
        path: URL path starting with `/`, e.g. `/2025-09-10/templates`.
        body: Request body. Use `"@path"` to read from a file (for multipart).
        ak, sk: Long-term AccessKey credentials.
        region: Region ID, e.g. `cn-hangzhou`.
        service: Service code; AgentRun uses `agentrun` on both planes.
        content_type: Override the canonical `content-type` (use
            `multipart/form-data; boundary=...` for uploads).
        query: Raw query string WITHOUT leading `?`, e.g. `path=/foo&depth=2`.
            Signer sorts and URI-encodes it for the canonical request.
        session_token: STS token; when set, an `X-Acs-Security-Token` header
            is added (still outside the signed set).

    Returns:
        Dict of header name → value. Callers should forward these verbatim
        to the HTTP client.
    """
    if not ak or not sk:
        raise ValueError("ak and sk are required")
    if not region:
        raise ValueError("region is required")

    method = method.upper()
    now = datetime.datetime.now(datetime.timezone.utc)
    date_time = now.strftime("%Y%m%dT%H%M%SZ")
    date = now.strftime("%Y%m%d")

    body_bytes = _read_body(body)
    body_hash = _sha256_hex(body_bytes)
    canonical_query = _canonical_query_string(query)

    # Canonical headers: name lowercase, value trimmed, sorted by name,
    # trailing newline after each line INCLUDING the last (per §2.2 of
    # api-signing.md).
    canonical_headers = "".join(
        f"{name}:{value}\n"
        for name, value in (
            ("content-type", content_type),
            ("host", host),
            ("x-acs-content-sha256", body_hash),
            ("x-acs-date", date_time),
        )
    )
    signed_headers = ";".join(name for name, _ in _SIGNED_HEADERS)

    canonical_request = (
        f"{method}\n{path}\n{canonical_query}\n{canonical_headers}{signed_headers}\n{body_hash}"
    )
    cr_hash = _sha256_hex(canonical_request.encode("utf-8"))

    credential_scope = f"{date}/{region}/{service}/aliyun_v4_request"
    string_to_sign = (
        f"ACS3-HMAC-SHA256\n{date_time}\n{credential_scope}\n{cr_hash}"
    )

    signing_key = _derive_signing_key(sk, date, region, service)
    signature = _hmac_sha256(signing_key, string_to_sign).hex()

    headers: dict[str, str] = {
        "Authorization": (
            f"ACS3-HMAC-SHA256 "
            f"Credential={ak}/{credential_scope}, "
            f"SignedHeaders={signed_headers}, "
            f"Signature={signature}"
        ),
        "X-Acs-Date": date_time,
        "X-Acs-Content-Sha256": body_hash,
        "Content-Type": content_type,
    }
    if session_token:
        headers["X-Acs-Security-Token"] = session_token
    return headers


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Sign an AgentRun HTTP request with ACS3-HMAC-SHA256."
    )
    p.add_argument("--method", required=True, help="HTTP method (POST/GET/PUT/PATCH/DELETE)")
    p.add_argument("--host", required=True, help="Endpoint host, e.g. agentrun.cn-hangzhou.aliyuncs.com")
    p.add_argument("--path", required=True, help="URL path beginning with '/'")
    p.add_argument(
        "--body",
        default="",
        help='Request body as a string, or "@/path/to/file" to read from disk',
    )
    p.add_argument("--ak", required=True, help="ALIBABA_CLOUD_ACCESS_KEY_ID")
    p.add_argument("--sk", required=True, help="ALIBABA_CLOUD_ACCESS_KEY_SECRET")
    p.add_argument("--region", required=True, help="ALIBABA_CLOUD_REGION_ID (e.g. cn-hangzhou)")
    p.add_argument("--service", default="agentrun", help="Service code (default: agentrun)")
    p.add_argument(
        "--content-type",
        default="application/json",
        help="Override canonical Content-Type (e.g. multipart/form-data; boundary=...)",
    )
    p.add_argument(
        "--query",
        default="",
        help="Raw query string without leading '?' (e.g. path=/foo&depth=2); will be sorted and URL-encoded into the canonical request",
    )
    p.add_argument(
        "--session-token",
        default=None,
        help="Optional STS token; adds X-Acs-Security-Token header",
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    try:
        headers = sign(
            method=args.method,
            host=args.host,
            path=args.path,
            body=args.body,
            ak=args.ak,
            sk=args.sk,
            region=args.region,
            service=args.service,
            content_type=args.content_type,
            query=args.query,
            session_token=args.session_token,
        )
    except (ValueError, OSError) as exc:
        print(f"sign: {exc}", file=sys.stderr)
        return 1
    for name, value in headers.items():
        print(f"{name}: {value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
