#!/usr/bin/env bash
# Code generated by alicloud-skill-generator; DO NOT EDIT manually.
# Operation:    WebSocketTTY (Safety Gate)
# Transport:    WSS (HTTP upgrade)
# Endpoint:     wss://${ACCOUNT}.agentrun-data.${REGION}.aliyuncs.com/sandboxes/${SANDBOX_ID}/processes/tty?protocol=json&tenantId=${ACCOUNT}
# Plane:        data
# CLI Support:  sdk-only (no aliyun CLI / Go SDK; HTTP + ACS3 signing required)
# Reference:    alicloud-agentrun-ops/SKILL.md §Operation: WebSocket TTY (Safety Gate)
#
# SAFETY GATE: interactive TTY gives FULL SHELL ACCESS to the sandbox.
#   - Set CONFIRM=yes to acknowledge the risk.
#   - The script does NOT perform the connect itself; it prints the signed
#     WSS URL and a ready-to-run websocat / wscat / wstest command.
#   - Authentication: ACS3-HMAC-SHA256 over the upgrade request (Authorization
#     header is forwarded to the WebSocket subprotocol).
#
# Requires external client: websocat, wscat, or any WS client that lets you
# set the Authorization header.

set -euo pipefail

# ---- Safety gate ----
if [ "${CONFIRM:-no}" != "yes" ]; then
  echo "ERROR: WebSocketTTY provides unrestricted shell access to the sandbox." >&2
  echo "       Set CONFIRM=yes to print the signed connection URL." >&2
  exit 64
fi

# ---- Credentials (NEVER hardcode; read from env) ----
: "${ALIBABA_CLOUD_ACCESS_KEY_ID:?missing ALIBABA_CLOUD_ACCESS_KEY_ID}"
: "${ALIBABA_CLOUD_ACCESS_KEY_SECRET:?missing ALIBABA_CLOUD_ACCESS_KEY_SECRET}"
: "${ALIBABA_CLOUD_REGION_ID:?missing ALIBABA_CLOUD_REGION_ID}"
: "${ALIBABA_CLOUD_ACCOUNT_ID:?missing ALIBABA_CLOUD_ACCOUNT_ID}"

# ---- Operation parameters (override via env) ----
: "${SANDBOX_ID:?missing SANDBOX_ID}"

# ---- Build the upgrade request (path = /tty?protocol=json&tenantId=...) ----
# The signer must see the FULL path including the query, so we encode the
# query into --query and leave the path empty-of-query.
HOST="${ALIBABA_CLOUD_ACCOUNT_ID}.agentrun-data.${ALIBABA_CLOUD_REGION_ID}.aliyuncs.com"
PATH_PART="/sandboxes/${SANDBOX_ID}/processes/tty"
QUERY="protocol=json&tenantId=${ALIBABA_CLOUD_ACCOUNT_ID}"
WSS_URL="wss://${HOST}${PATH_PART}?${QUERY}"

# ---- Sign + print headers (Authorization is what the WS client must send) ----
SIGNER="$(cd "$(dirname "$0")" && pwd)/sign.py"
echo "=== Signed WSS URL ==="
echo "$WSS_URL"
echo
echo "=== Signed headers (pass to your WS client as upgrade headers) ==="
python3 "$SIGNER" \
  --method GET \
  --host "$HOST" \
  --path "$PATH_PART" \
  --query "$QUERY" \
  --body "" \
  --ak "$ALIBABA_CLOUD_ACCESS_KEY_ID" \
  --sk "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" \
  --region "$ALIBABA_CLOUD_REGION_ID" \
  ${ALIBABA_CLOUD_SECURITY_TOKEN:+--session-token "$ALIBABA_CLOUD_SECURITY_TOKEN"}
echo
echo "=== Connect with websocat (if installed) ==="
echo "  websocat -H 'Authorization: <paste Authorization value above>' \\"
echo "           -H 'X-Acs-Parent-Id: ${ALIBABA_CLOUD_ACCOUNT_ID}' \\"
echo "           '$WSS_URL'"
echo
echo "Audit recommendation: log session start time, duration, and sandbox id."
