// Code generated by alicloud-link-cruise; DO NOT EDIT manually.
// Operation:    GetQueryOptimizeExecErrorSample
// SDK Method:   client.GetQueryOptimizeExecErrorSample
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       RegionId 字段仍从 env 读取。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
//
// Usage:
//   cd alicloud-link-cruise/assets/code-snippets
//   INSTANCE_ID=rm-xxx go run das_slow_query.go

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	instanceID := os.Getenv("INSTANCE_ID")
	if instanceID == "" {
		log.Fatal("INSTANCE_ID is required")
	}

	// 1. 查询慢 SQL 统计数据
	statsReq := &das.GetQueryOptimizeExecErrorStatsRequest{
		Engine:     tea.String("mysql"),
		InstanceId: tea.String(instanceID),
		Time:       tea.String(GetDefaultTimeRange()),
		PageNo:     tea.Int32(1),
		PageSize:   tea.Int32(10),
	}

	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	statsResp, err := c.GetQueryOptimizeExecErrorStats(statsReq)
	if err != nil {
		log.Fatalf("GetQueryOptimizeExecErrorStats failed: %v", err)
	}

	// 2. 取慢 SQL 样本
	samplesReq := &das.GetQueryOptimizeExecErrorSampleRequest{
		Engine:     tea.String("mysql"),
		InstanceId: tea.String(instanceID),
		Time:       tea.String(GetDefaultTimeRange()),
	}

	samplesResp, err := c.GetQueryOptimizeExecErrorSample(samplesReq)
	if err != nil {
		log.Fatalf("GetQueryOptimizeExecErrorSample failed: %v", err)
	}

	// 3. 组合输出
	result := map[string]interface{}{
		"stats":   statsResp.Body,
		"samples": samplesResp.Body,
	}

	out, _ := json.MarshalIndent(result, "", "  ")
	fmt.Println(string(out))

	// 关键字段提示:
	// $.stats.Data.List[].SqlId       -> SQL ID
	// $.stats.Data.List[].ErrorCount  -> 错误次数
	// $.samples.Data.List[].SqlText   -> 慢 SQL 原文
	// $.samples.Data.List[].Database  -> 所在数据库
}

// GetDefaultTimeRange returns a default time range (last 24h) as a string.
func GetDefaultTimeRange() string {
	return "172800" // 最近 24 小时的时间戳范围（简化处理，巡检用）
}