// Code generated by alicloud-link-cruise; DO NOT EDIT manually.
// Operation:    CreateCacheAnalysisJob + DescribeCacheAnalysisJob
// SDK Method:   client.CreateCacheAnalysisJob / client.DescribeCacheAnalysisJob
// API Version:  2020-01-16
// NOTE: DAS is single-region; endpoint固定为 cn-shanghai。
//       仅适用于 Redis / Tair 实例。
// CLI Support:  sdk-only (no aliyun CLI equivalent)
//
// Usage:
//   cd alicloud-link-cruise/assets/code-snippets
//   INSTANCE_ID=r-xxx NODE_ID=node-0 go run das_cache_analysis.go

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"time"

	das "github.com/alibabacloud-go/das-20200116/v5/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	instanceID := os.Getenv("INSTANCE_ID")
	if instanceID == "" {
		log.Fatal("INSTANCE_ID is required")
	}
	nodeID := os.Getenv("NODE_ID") // 可选：集群版指定节点

	c, err := NewClient("das.cn-shanghai.aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	// 1. 创建缓存分析任务
	createReq := &das.CreateCacheAnalysisJobRequest{
		InstanceId: tea.String(instanceID),
	}
	if nodeID != "" {
		createReq.NodeId = tea.String(nodeID)
	}

	createResp, err := c.CreateCacheAnalysisJob(createReq)
	if err != nil {
		log.Fatalf("CreateCacheAnalysisJob failed: %v", err)
	}

	jobID := createResp.Body.Data.JobId
	fmt.Fprintf(os.Stderr, "[INFO] 缓存分析任务已创建: %s\n", tea.StringValue(jobID))

	// 2. 轮询任务结果（最多等 60 秒）
	var lastResult interface{}
	for i := 0; i < 12; i++ {
		time.Sleep(5 * time.Second)

		describeReq := &das.DescribeCacheAnalysisJobRequest{
			InstanceId: tea.String(instanceID),
			JobId:      jobID,
		}

		describeResp, err := c.DescribeCacheAnalysisJob(describeReq)
		if err != nil {
			log.Printf("[WARN] 轮询第 %d 次失败: %v", i+1, err)
			continue
		}

		lastResult = describeResp.Body

		// 任务完成标志
		if describeResp.Body.Code != nil && tea.StringValue(describeResp.Body.Code) == "200" {
			break
		}
	}

	if lastResult == nil {
		log.Fatal("缓存分析任务超时")
	}

	out, _ := json.MarshalIndent(lastResult, "", "  ")
	fmt.Println(string(out))

	// 关键字段提示:
	// $.Data.BigKeys[]           -> 大 key 列表
	// $.Data.BigKeys[].Key       -> key 名称
	// $.Data.BigKeys[].Db        -> 所在 DB
	// $.Data.BigKeys[].KeyType   -> key 类型 (string/hash/list/set/zset)
	// $.Data.BigKeys[].Size      -> key 大小 (bytes)
}