// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    CreateInstance
// SDK Method:   client.CreateInstance
// API Version:  2017-06-13
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/elasticsearch/developer-reference/api-elasticsearch-2017-06-13-createinstance
//
// Usage:
//   cd alicloud-elasticsearch-ops/assets/code-snippets
//   export ALIBABA_CLOUD_REGION_ID=cn-hangzhou
//   export INSTANCE_NAME=my-es-cluster
//   export ES_VERSION=7.10_aliyun
//   export NODE_SPEC=elasticsearch.sn2ne.large
//   export DATA_NODE_AMOUNT=3
//   export DISK_TYPE=cloud_ssd
//   export DISK_SIZE=100
//   export VPC_ID=vpc-xxx
//   export VSWITCH_ID=vsw-xxx
//   export PASSWORD='YourPwd123!'
//   export CHARGE_TYPE=PostPaid
//   go run create_elasticsearch_instance.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	elasticsearch "github.com/alibabacloud-go/elasticsearch-20170613/v6/client"
	"github.com/alibabacloud-go/tea/tea"
)

// atoiOr parses an env var as int with a default fallback.
func atoiOr(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil {
		return def
	}
	return n
}

func main() {
	// 1. 构造请求 — 所有字段都从 env 读取，演示值通过环境变量覆盖
	req := &elasticsearch.CreateInstanceRequest{
		RegionId:       tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		InstanceName:   tea.String(os.Getenv("INSTANCE_NAME")),
		EsVersion:      tea.String(os.Getenv("ES_VERSION")),
		NodeSpec:       tea.String(os.Getenv("NODE_SPEC")),
		DataNodeAmount: tea.Int32(int32(atoiOr(os.Getenv("DATA_NODE_AMOUNT"), 3))),
		DiskType:       tea.String(os.Getenv("DISK_TYPE")),
		DiskSize:       tea.Int32(int32(atoiOr(os.Getenv("DISK_SIZE"), 100))),
		VpcId:          tea.String(os.Getenv("VPC_ID")),
		VswitchId:      tea.String(os.Getenv("VSWITCH_ID")),
		Password:       tea.String(os.Getenv("PASSWORD")),
		ChargeType:     tea.String(os.Getenv("CHARGE_TYPE")),
	}

	// 2. 调用 Client — endpoint 也从 env 拼接
	c, err := NewClient("elasticsearch." + os.Getenv("ALIBABA_CLOUD_REGION_ID") + ".aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.CreateInstance(req)
	if err != nil {
		// 错误信息必须包含 RequestId, 便于回溯
		log.Fatalf("CreateInstance failed: %v", err)
	}

	// 3. 序列化输出 (便于 Agent 解析)
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示 (供 Agent 提取)
	// $.body.Result.InstanceId   -> 新建 ES 实例 ID
	// $.body.Result.Status       -> 初始状态 (Activating)
	// $.body.RequestId           -> 用于工单/日志关联
}
