// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    DeleteInstance
// SDK Method:   client.DeleteInstance
// API Version:  2017-06-13
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/elasticsearch/developer-reference/api-elasticsearch-2017-06-13-deleteinstance
//
// Usage:
//   cd alicloud-elasticsearch-ops/assets/code-snippets
//   INSTANCE_ID=es-cn-xxx go run delete_elasticsearch_instance.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	elasticsearch "github.com/alibabacloud-go/elasticsearch-20170613/v6/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求 (字段名与 OpenAPI Request Schema 1:1 对齐)
	// ⚠️ DESTRUCTIVE: DeleteInstance is IRREVERSIBLE. All data, indices,
	// and snapshots owned by this instance will be lost.
	req := &elasticsearch.DeleteInstanceRequest{
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
	}

	// 2. 调用 Client
	c, err := NewClient("elasticsearch." + os.Getenv("ALIBABA_CLOUD_REGION_ID") + ".aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.DeleteInstance(req)
	if err != nil {
		// 错误信息必须包含 RequestId, 便于回溯
		log.Fatalf("DeleteInstance failed: %v", err)
	}

	// 3. 序列化输出 (便于 Agent 解析)
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示 (供 Agent 提取)
	// $.body.Result    -> DeleteInstanceResponse 包含删除结果
	// $.body.RequestId -> 用于工单/日志关联
}
