// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    DescribeInstance
// SDK Method:   client.DescribeInstance
// API Version:  2017-06-13
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/elasticsearch/developer-reference/api-elasticsearch-2017-06-13-describeinstance
//
// Usage:
//   cd alicloud-elasticsearch-ops/assets/code-snippets
//   INSTANCE_ID=es-cn-xxx go run describe_elasticsearch_instance.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	elasticsearch "github.com/alibabacloud-go/elasticsearch-20170613/v6/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求 (字段名与 OpenAPI Request Schema 1:1 对齐)
	req := &elasticsearch.DescribeInstanceRequest{
		InstanceId: tea.String(os.Getenv("INSTANCE_ID")),
	}

	// 2. 调用 Client
	c, err := NewClient("elasticsearch." + os.Getenv("ALIBABA_CLOUD_REGION_ID") + ".aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.DescribeInstance(req)
	if err != nil {
		// 错误信息必须包含 RequestId, 便于回溯
		log.Fatalf("DescribeInstance failed: %v", err)
	}

	// 3. 序列化输出 (便于 Agent 解析)
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示 (供 Agent 提取)
	// $.body.Result.InstanceId   -> 实例 ID
	// $.body.Result.Status       -> Normal | Activating | Inactive
	// $.body.Result.EsVersion    -> ES 版本 (如 7.10_aliyun)
	// $.body.Result.NodeAmount   -> 数据节点数
	// $.body.Result.Endpoints    -> 连接端点列表
	// $.body.RequestId           -> 用于工单/日志关联
}
