// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    ListInstance
// SDK Method:   client.ListInstance
// API Version:  2017-06-13
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/elasticsearch/developer-reference/api-elasticsearch-2017-06-13-listinstance
//
// Usage:
//   cd alicloud-elasticsearch-ops/assets/code-snippets
//   go run list_elasticsearch_instances.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	elasticsearch "github.com/alibabacloud-go/elasticsearch-20170613/v6/client"
	"github.com/alibabacloud-go/tea/tea"
)

func main() {
	// 1. 构造请求 (字段名与 OpenAPI Request Schema 1:1 对齐)
	req := &elasticsearch.ListInstanceRequest{
		RegionId:   tea.String(os.Getenv("ALIBABA_CLOUD_REGION_ID")),
		PageNumber: tea.Int32(1),
		PageSize:   tea.Int32(20),
		// Optional filter: 按状态过滤
		// Status: tea.String("Normal"),
	}

	// 2. 调用 Client
	c, err := NewClient("elasticsearch." + os.Getenv("ALIBABA_CLOUD_REGION_ID") + ".aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.ListInstance(req)
	if err != nil {
		// 错误信息必须包含 RequestId, 便于回溯
		log.Fatalf("ListInstance failed: %v", err)
	}

	// 3. 序列化输出 (便于 Agent 解析)
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示 (供 Agent 提取)
	// $.body.Result[].instanceId -> 实例 ID 列表
	// $.body.Result[].status     -> 实例状态
	// $.body.TotalCount          -> 总数（分页依据）
	// $.body.PageNumber          -> 当前页码
	// $.body.RequestId           -> 用于工单/日志关联
}
