// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Reference: references/integration.md §Go Runtime Bootstrap
//
// This file provides a shared NewClient factory for all Elasticsearch operation
// snippets. It does NOT define a `main` function — each operation snippet
// file has its own `main` entry point.
//
// To run a snippet, compile this file together with the target snippet:
//
//	go run create_elasticsearch_instance.go main.go
package main

import (
	"fmt"
	"os"

	openapi "github.com/alibabacloud-go/darabonba-openapi/v2/client"
	elasticsearch "github.com/alibabacloud-go/elasticsearch-20170613/v6/client"
)

// NewClient constructs an Elasticsearch client using env credentials.
// MUST be the only place credentials are referenced; never log SK.
func NewClient(endpoint string) (*elasticsearch.Client, error) {
	ak := os.Getenv("ALIBABA_CLOUD_ACCESS_KEY_ID")
	sk := os.Getenv("ALIBABA_CLOUD_ACCESS_KEY_SECRET")
	if ak == "" || sk == "" {
		return nil, fmt.Errorf("missing ALIBABA_CLOUD_ACCESS_KEY_ID or ALIBABA_CLOUD_ACCESS_KEY_SECRET")
	}

	config := &openapi.Config{
		AccessKeyId:     &ak,
		AccessKeySecret: &sk,
		Endpoint:        &endpoint,
	}
	return elasticsearch.NewClient(config)
}
