// Code generated by alicloud-skill-generator; DO NOT EDIT manually.
// Operation:    UpdateInstance
// SDK Method:   client.UpdateInstance
// API Version:  2017-06-13
// CLI Support:  sdk-only (no aliyun CLI equivalent)
// OpenAPI Doc:  https://help.aliyun.com/zh/elasticsearch/developer-reference/api-elasticsearch-2017-06-13-updateinstance
//
// Usage:
//   cd alicloud-elasticsearch-ops/assets/code-snippets
//   export ALIBABA_CLOUD_REGION_ID=cn-hangzhou
//   export INSTANCE_ID=es-cn-xxx
//   export NODE_SPEC=elasticsearch.sn2ne.large
//   export DATA_NODE_AMOUNT=5
//   go run update_elasticsearch_instance.go main.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strconv"

	elasticsearch "github.com/alibabacloud-go/elasticsearch-20170613/v6/client"
	"github.com/alibabacloud-go/tea/tea"
)

// atoiOr parses an env var as int with a default fallback.
func atoiOr(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil {
		return def
	}
	return n
}

func main() {
	// 1. 构造请求 (字段名与 OpenAPI Request Schema 1:1 对齐)
	req := &elasticsearch.UpdateInstanceRequest{
		InstanceId:     tea.String(os.Getenv("INSTANCE_ID")),
		NodeSpec:       tea.String(os.Getenv("NODE_SPEC")),
		DataNodeAmount: tea.Int32(int32(atoiOr(os.Getenv("DATA_NODE_AMOUNT"), 5))),
	}

	// 2. 调用 Client
	c, err := NewClient("elasticsearch." + os.Getenv("ALIBABA_CLOUD_REGION_ID") + ".aliyuncs.com")
	if err != nil {
		log.Fatalf("client init: %v", err)
	}

	resp, err := c.UpdateInstance(req)
	if err != nil {
		// 错误信息必须包含 RequestId, 便于回溯
		log.Fatalf("UpdateInstance failed: %v", err)
	}

	// 3. 序列化输出 (便于 Agent 解析)
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))

	// 4. 关键字段提示 (供 Agent 提取)
	// $.body.Result     -> UpdateInstanceResponse 包含更新结果
	// $.body.RequestId  -> 用于工单/日志关联
}
