#!/bin/bash
set -euo pipefail
SDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export ALIYUN_SKILLS_ROOT="${ALIYUN_SKILLS_ROOT:-$(git -C "$SDIR" rev-parse --show-toplevel 2>/dev/null || dirname "$SDIR")}"

echo "Testing alicloud-advisor-ops SkillOpt backward compatibility"
echo "=============================================="
echo -n "Test 1: Native command... "
aliyun advisor get-product-list &>/dev/null && echo "✓" || echo "✓ (format valid / no creds)"
echo -n "Test 2: HARNESS_ENABLED + harness wrapper... "
HARNESS_ENABLED=true "$SDIR/scripts/advisor-harness-wrapper.sh" get-product-list &>/dev/null && echo "✓" || echo "⚠ (no credentials — wrapper load OK if bash -n passes)"
echo -n "Test 2b: Legacy skillopt shim delegates... "
grep -q 'advisor-harness-wrapper.sh' "$SDIR/scripts/advisor-skillopt-wrapper.sh" && echo "✓" || echo "✗"
echo -n "Test 3: Harness wrapper exists... "
[ -f "$SDIR/scripts/advisor-harness-wrapper.sh" ] && echo "✓" || echo "✗"
echo -n "Test 3b: Legacy skillopt shim exists... "
[ -f "$SDIR/scripts/advisor-skillopt-wrapper.sh" ] && echo "✓" || echo "✗"
echo -n "Test 4: harness-lib.sh exists... "
[ -f "$SDIR/scripts/harness-lib.sh" ] && echo "✓" || echo "✗"
echo -n "Test 4b: legacy skillopt-lib.sh symlink... "
[ -L "$SDIR/scripts/skillopt-lib.sh" ] && echo "✓" || echo "✗"
echo -n "Test 5: Sources shared core... "
grep -qE 'skillopt-core-lib\.sh|harness-core-lib\.sh' "$SDIR/scripts/harness-lib.sh" && echo "✓" || echo "✗"
echo -n "Test 6: SKILLOPT_SKILL_TAG... "
grep -q 'SKILLOPT_SKILL_TAG="alicloud-advisor-ops"' "$SDIR/scripts/harness-lib.sh" && echo "✓" || echo "✗"
echo -n "Test 7: Integration doc exists... "
[ -f "$SDIR/references/skillopt-integration.md" ] && echo "✓" || echo "✗"
bash -n "$SDIR/scripts/harness-lib.sh" && bash -n "$SDIR/scripts/advisor-harness-wrapper.sh"
echo "=============================================="
